org: maharris1011
app: cantstopcolumbus-api

service: csc-gateway

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

resources:
  Resources:
    CSCGW:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: CSCGW
  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: CSCGW
      Export:
        Name: CSCGW-restApiId
    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - CSCGW
          - RootResourceId
      Export:
        Name: CSCGW-rootResourceId