export default class AirtableDataSource {
  list(offset = null) {
    return {
      records: [
        {
          id: "recELrc7zc3IhDNrQ",
          fields: {
            Category: "Access to information",
            Ideas: [
              "recNs8VPSnfeHQZqc",
              "reclxZ6KC0YC45HTr",
              "recdPooEYhbkMbs9f",
              "recl2QhtzS496GW4z",
              "recrhFQVceYWChI3V",
              "recjSE6TiQXNrdNGI",
              "recVlkUImACacVxmF",
              "rec12MF90Wr1wgJXQ",
              "recq9sfwSLVDUbKeR",
              "recesxufjVVF2kC77",
              "recEAmo8zYJmF5PCK",
              "rec6d0aIEUfph04ZE",
              "rec4Wxc7kzv5hLXLC",
              "recJsrkOAlr9bG0vT"
            ],
            "Needs Assessment - Non Profit": [
              "rece5kFNLTrEoZUxf",
              "recyVkixGwpjhEfVR"
            ],
            People: [
              "recmYqhamra0ZLtOQ",
              "rec2wtAPOT0GJBuEY",
              "recdJiJ5FSAWWUXB6",
              "rec6GEIEeZ2SOQEBc",
              "recPjmi2zpPKg9ykt",
              "recNdxKgCiIGOkOVd",
              "recMCNIcpOA7zKHWl",
              "recUCTBWVdiWnytUa",
              "recUf07pjkLBDrtue",
              "recig0rbKaL9DsV3y",
              "recJRBgvbDKQjGbg7",
              "rec8OA5FqaebAvPbE",
              "rechEi2C9VoKN2IW8",
              "recI34041cZEoLENr",
              "recApBoM1xAFE8F0b",
              "rec2VZkId9LIYlHbZ",
              "rechqHPZTkiaAcTHw",
              "recm2JqUDRktt7JdK",
              "recgfoPOOGJNNmV6l",
              "recT6oVeGp7IM3xJK",
              "recLtUcG9aqPeTSO7",
              "recbgNOeIGvXfWepI",
              "recKPA59GConLg1eP",
              "rec4xgOrVPDncSVEn",
              "rec0K6Xt8iIvF13ET",
              "rec4kS5BRrcnjiIYj",
              "rec4ViUtrtYIbo32a",
              "recFRJWER1C0SSav1",
              "recTv3CwcJOkDnNJP",
              "recYsl1soxn3HxIKJ",
              "recujAXebSk5Ujq41",
              "rec6w5SuzNUql7a5h",
              "rec8MoiNcEOPRB0tV",
              "recP9WBrwb0iFB3Hq",
              "recKJvG0BBMBNQizi",
              "recyJqqCygE3oJAUe",
              "recDfHn1iBANEipik",
              "recl3BVTHdhsthFde",
              "reco5fha0Q5yeN1ox",
              "recizpYQs2hHjRq8Y",
              "recMTroBTuVpJjQ0V",
              "recB9dL9yIkK0h9OX",
              "rec0xQhnfzhLhKqeE",
              "recr557mNENCCmhhi",
              "recGlNMXkmG9pDRhh",
              "reczC0AYyool0ZO5k",
              "recbbOcGdMtkW8OnZ",
              "receAroVIhjgknYzr",
              "recluw4E23dDhsM53",
              "rec8PSiedDCrUStRG",
              "recZ9BHogrPFLtDBq",
              "rechoONdy3FH7QrVe",
              "recEpQzLkBaCaBvLK",
              "recJX6iEB9FqNzO97",
              "recmtrU7mvPzOI3rw",
              "rec0qpjKYXLwGofIB",
              "recD5L5CGTYbIIJjS",
              "recmMbftwNDGuHvfs",
              "recuPtSlOl4FKBdT3",
              "rec1fE0F8mMUKU5MT",
              "recdHM1QePATyOkEC",
              "rec36eITWJMxv95JL",
              "recpBD0xs0Ex63o1R"
            ],
            Problems: ["recekRiGZjFFwUvzD", "recifvrOOiPG37hpl"],
            "Projects copy": [
              "recjsfWZimxxbVR3k",
              "rec0l2msl1e2lwMiS",
              "recoSmyDhhzFAO2CV",
              "reciP6QoXINcVMH5s",
              "recqxHyuBrAudGWPE",
              "recq2yJdyjG1fhb0M",
              "recv9aHgRcxv3MZa4",
              "recbdICsDlRhqBjVR",
              "rec62u7TZn3TFRYT3",
              "recJA4QSypleOG4yX",
              "recSsQnzROR6Qremp",
              "rec9WfERj07XqmcHP",
              "recwhniFbFAOLSXZ8"
            ]
          },
          createdTime: "2020-03-18T16:18:20.000Z"
        },
        {
          id: "recj6nyTmLv80r8hl",
          fields: {
            Category: "Education",
            Ideas: [
              "rec4fWwYO8qF8HpmJ",
              "recyr7aKl2lpyIVq0",
              "rec0lQrUR6Vs96EOF",
              "rece3DwSY5bXeJCZK",
              "rec0ZezSMfZPx3dTm"
            ],
            "Needs Assessment - Non Profit": [
              "rece5kFNLTrEoZUxf",
              "recyVkixGwpjhEfVR",
              "recDvpbJfteLw3edf",
              "recxPnoGMeana0Rhh"
            ],
            People: [
              "rectXJTCWGYw2gXNF",
              "recmYqhamra0ZLtOQ",
              "rec2wtAPOT0GJBuEY",
              "recHlDSO8lWeUNcqR",
              "recx70H3AjVXxFBkn",
              "reckf95OKkqXROvHx",
              "rectIqvRSxavmttOp",
              "recWfwGM2vtYCvPrD",
              "rec8N2WPza7wcGZaK",
              "recYyHpkPN0JGyVcG",
              "recBfAubaOo7nCKW5",
              "recUf07pjkLBDrtue",
              "rec18DmmcsRjpLZCe",
              "recvNquC9qUybOKrA",
              "rec0CjyQfbNjiQkNI",
              "recrblX5n97ILFlAu",
              "recRbyUvLQtSKU8uc",
              "recI34041cZEoLENr",
              "recApBoM1xAFE8F0b",
              "rechqHPZTkiaAcTHw",
              "recohg7KUR0aj7ojm",
              "rec2I8f6mG9wRFnVI",
              "recuXNPwymPe5ujsa",
              "recgfoPOOGJNNmV6l",
              "recACSonSkeb2y23Z",
              "recT6oVeGp7IM3xJK",
              "rechkNjWkQyuiCfIr",
              "rec73O3GQEhG0m1lG",
              "recKPA59GConLg1eP",
              "rec0K6Xt8iIvF13ET",
              "rec4kS5BRrcnjiIYj",
              "recYsl1soxn3HxIKJ",
              "reczC3OYqZtDrpOmv",
              "rec2MVyeYpGdjbcUF",
              "recJvJvfmXroiBaMY",
              "recDfHn1iBANEipik",
              "recGQSkMvJvhHjzGg",
              "recPejnadU0j3FP6e",
              "reco5fha0Q5yeN1ox",
              "recK1r96mt8YWrPy8",
              "recMTroBTuVpJjQ0V",
              "rec0xQhnfzhLhKqeE",
              "recCJUeLPBWj9IKyj",
              "recBZH5a6kZ01kGz7",
              "recRlNdvziwEcrUDT",
              "recGlNMXkmG9pDRhh",
              "rec2oqkoiq58rHo7H",
              "recbbOcGdMtkW8OnZ",
              "recCe1QwAYMy46imW",
              "rec5qr6wEjcJwmfuU",
              "recLhYywhwkgJi7az",
              "recrAsJdw4PvoSwAW",
              "recStf6tKfw8WpSF2",
              "recmtrU7mvPzOI3rw",
              "recHEOGySpNWTu11J",
              "recyHifhdzXkrHeYa",
              "recud1tl4Bwn0RRRx",
              "recmMbftwNDGuHvfs",
              "recFei7FBcpp8jnIG",
              "recFMDUNomwrIWx4t",
              "rec0ByYAlXtH2e8Ng",
              "recz4PNz47qSBbit4",
              "recuPtSlOl4FKBdT3",
              "rec36eITWJMxv95JL"
            ],
            Problems: ["recifvrOOiPG37hpl"],
            "Projects copy": [
              "recDrPCuktXhHjamd",
              "rec9fEYINz2xhiEiW",
              "recj3lYCXwNPnkRVX",
              "rec5lyTEQxxkiHTKS"
            ]
          },
          createdTime: "2020-03-17T13:10:26.000Z"
        },
        {
          id: "recGtk59cVdXq4tyB",
          fields: {
            Category: "Elderly & At Risk Populations",
            Ideas: [
              "reczyMKJgEGlhxrMG",
              "reciKhBAoCQZ2HtEy",
              "rec7mW4eS2O2u7U31",
              "recQTfm5a1k6f1mLE"
            ],
            "Needs Assessment - Non Profit": [
              "reciKIs2FXjTzxRC6",
              "recyVkixGwpjhEfVR",
              "recwkjdsRLm7rCRxo",
              "recKRTrjf6WOjo7hB",
              "recDvpbJfteLw3edf",
              "recxPnoGMeana0Rhh"
            ],
            People: [
              "rec6GEIEeZ2SOQEBc",
              "recHlDSO8lWeUNcqR",
              "recPjmi2zpPKg9ykt",
              "rectIqvRSxavmttOp",
              "recWfwGM2vtYCvPrD",
              "rec8N2WPza7wcGZaK",
              "recYyHpkPN0JGyVcG",
              "recBfAubaOo7nCKW5",
              "rec0CjyQfbNjiQkNI",
              "rec8OA5FqaebAvPbE",
              "rechEi2C9VoKN2IW8",
              "recLwyWnqXAzT2moP",
              "recRbyUvLQtSKU8uc",
              "recI34041cZEoLENr",
              "recfKutPXzulWdFnJ",
              "rec6BGcZTTkeqmbw8",
              "recFqHvM1XH8e9XvY",
              "recCghS8wPYhRoXqO",
              "recTVaGt9dF3akHwK",
              "rec4kS5BRrcnjiIYj",
              "recTTTKTFU8Qhq86c",
              "rec4ViUtrtYIbo32a",
              "recujAXebSk5Ujq41",
              "rec2MVyeYpGdjbcUF",
              "recGQSkMvJvhHjzGg",
              "recGenCiKQXB0KtHr",
              "recK1r96mt8YWrPy8",
              "rec0xQhnfzhLhKqeE",
              "recCJUeLPBWj9IKyj",
              "recBZH5a6kZ01kGz7",
              "recGlNMXkmG9pDRhh",
              "receAroVIhjgknYzr",
              "recluw4E23dDhsM53",
              "recZ9BHogrPFLtDBq",
              "recLhYywhwkgJi7az",
              "recEpQzLkBaCaBvLK",
              "rech6Xe3VqS24dcSt",
              "recFei7FBcpp8jnIG",
              "recjde29WvYqt2c0F",
              "reccR1Z2BNwlD8GcT",
              "recI7k2FeJPGw7JB9",
              "rec36eITWJMxv95JL"
            ],
            "Projects copy": ["recEyuctf5idq8GIT", "recnKZ3kn3sRbiIAL"]
          },
          createdTime: "2020-03-17T12:03:01.000Z"
        }
      ],
      offset: "recGtk59cVdXq4tyB"
    }
  }

  read(id) {
    return {
      id: id,
      fields: {
        Category: "Access to information",
        Ideas: [
          "recNs8VPSnfeHQZqc",
          "reclxZ6KC0YC45HTr",
          "recdPooEYhbkMbs9f",
          "recl2QhtzS496GW4z",
          "recrhFQVceYWChI3V",
          "recjSE6TiQXNrdNGI",
          "recVlkUImACacVxmF",
          "rec12MF90Wr1wgJXQ",
          "recq9sfwSLVDUbKeR",
          "recesxufjVVF2kC77",
          "recEAmo8zYJmF5PCK",
          "rec6d0aIEUfph04ZE",
          "rec4Wxc7kzv5hLXLC",
          "recJsrkOAlr9bG0vT"
        ],
        "Needs Assessment - Non Profit": [
          "rece5kFNLTrEoZUxf",
          "recyVkixGwpjhEfVR"
        ],
        People: [
          "recmYqhamra0ZLtOQ",
          "rec2wtAPOT0GJBuEY",
          "recdJiJ5FSAWWUXB6",
          "rec6GEIEeZ2SOQEBc",
          "recPjmi2zpPKg9ykt",
          "recNdxKgCiIGOkOVd",
          "recMCNIcpOA7zKHWl",
          "recUCTBWVdiWnytUa",
          "recUf07pjkLBDrtue",
          "recig0rbKaL9DsV3y",
          "recJRBgvbDKQjGbg7",
          "rec8OA5FqaebAvPbE",
          "rechEi2C9VoKN2IW8",
          "recI34041cZEoLENr",
          "recApBoM1xAFE8F0b",
          "rec2VZkId9LIYlHbZ",
          "rechqHPZTkiaAcTHw",
          "recm2JqUDRktt7JdK",
          "recgfoPOOGJNNmV6l",
          "recT6oVeGp7IM3xJK",
          "recLtUcG9aqPeTSO7",
          "recbgNOeIGvXfWepI",
          "recKPA59GConLg1eP",
          "rec4xgOrVPDncSVEn",
          "rec0K6Xt8iIvF13ET",
          "rec4kS5BRrcnjiIYj",
          "rec4ViUtrtYIbo32a",
          "recFRJWER1C0SSav1",
          "recTv3CwcJOkDnNJP",
          "recYsl1soxn3HxIKJ",
          "recujAXebSk5Ujq41",
          "rec6w5SuzNUql7a5h",
          "rec8MoiNcEOPRB0tV",
          "recP9WBrwb0iFB3Hq",
          "recKJvG0BBMBNQizi",
          "recyJqqCygE3oJAUe",
          "recDfHn1iBANEipik",
          "recl3BVTHdhsthFde",
          "reco5fha0Q5yeN1ox",
          "recizpYQs2hHjRq8Y",
          "recMTroBTuVpJjQ0V",
          "recB9dL9yIkK0h9OX",
          "rec0xQhnfzhLhKqeE",
          "recr557mNENCCmhhi",
          "recGlNMXkmG9pDRhh",
          "reczC0AYyool0ZO5k",
          "recbbOcGdMtkW8OnZ",
          "receAroVIhjgknYzr",
          "recluw4E23dDhsM53",
          "rec8PSiedDCrUStRG",
          "recZ9BHogrPFLtDBq",
          "rechoONdy3FH7QrVe",
          "recEpQzLkBaCaBvLK",
          "recJX6iEB9FqNzO97",
          "recmtrU7mvPzOI3rw",
          "rec0qpjKYXLwGofIB",
          "recD5L5CGTYbIIJjS",
          "recmMbftwNDGuHvfs",
          "recuPtSlOl4FKBdT3",
          "rec1fE0F8mMUKU5MT",
          "recdHM1QePATyOkEC",
          "rec36eITWJMxv95JL",
          "recpBD0xs0Ex63o1R"
        ],
        Problems: ["recekRiGZjFFwUvzD", "recifvrOOiPG37hpl"],
        "Projects copy": [
          "recjsfWZimxxbVR3k",
          "rec0l2msl1e2lwMiS",
          "recoSmyDhhzFAO2CV",
          "reciP6QoXINcVMH5s",
          "recqxHyuBrAudGWPE",
          "recq2yJdyjG1fhb0M",
          "recv9aHgRcxv3MZa4",
          "recbdICsDlRhqBjVR",
          "rec62u7TZn3TFRYT3",
          "recJA4QSypleOG4yX",
          "recSsQnzROR6Qremp",
          "rec9WfERj07XqmcHP",
          "recwhniFbFAOLSXZ8"
        ]
      },
      createdTime: "2020-03-18T16:18:20.000Z"
    }
  }
}
