export default class ActivityDataSource {
  list(offset = null) {
    return [
      {
        _table: {
          _base: {
            _airtable: { requestTimeout: 300000 },
            _id: "appEy2iTLwkkVlSjn"
          },
          id: null,
          name: "Activities"
        },
        id: "recj3QZqhAYtnE3Z2",
        _rawJson: {
          id: "recj3QZqhAYtnE3Z2",
          fields: {
            Activity: "Administration and documentation",
            People: [
              "recUsxYxovkjvJ9GU",
              "recd393lV15mkoHVC",
              "recsfWVZvXOlpuR8F",
              "recjgI71Eztoo75u6",
              "recnnckGJ8w8usZEO",
              "recNkesv5Kmm1Az57",
              "rechnJA7vTowW2b5y",
              "recJUxFSb0eBe3zce",
              "recT13WkVSxT3P8wY",
              "recddJKK6vbn1udyH",
              "recZCfbZTXQhziOJ1",
              "recFVlsjjUHuLuPK1",
              "recGGT9fk8vVfdgsb",
              "recVWBOQRQos2uQsa",
              "rechZemhPUNr4yniA",
              "recRPPSp7suRHXhxP",
              "rectbfqOfL1zXeXKk",
              "rec6wquMpQLtDlz6r",
              "recA5k6xzxVWUjLgW",
              "recaTJZ2XiIgYH19Z",
              "recT0EBER5SVNsuWD",
              "recI92yh0AaXxoTk2",
              "rec0hA6TZu6ZkGnTG",
              "rec7438mhJerzgRQV",
              "recJOPveB5eGDIQ2q",
              "rec7na42NMvUNY8G4",
              "recRi9Ku7eu2fMQAN",
              "recklxBF7DZ2gFUGD",
              "recowa3vO2VAambCw",
              "recWrEpqitVW4NPqS",
              "recUnrWGVQeKlNwfm",
              "rec6MyMavOMT8LLQW",
              "rect6krDlbYiIW3rk",
              "recHgEmSqkWwRI4iK",
              "recgQs2yFQudnL4XM"
            ]
          },
          createdTime: "2020-03-30T20:58:49.000Z"
        },
        fields: {
          Activity: "Administration and documentation",
          People: [
            "recUsxYxovkjvJ9GU",
            "recd393lV15mkoHVC",
            "recsfWVZvXOlpuR8F",
            "recjgI71Eztoo75u6",
            "recnnckGJ8w8usZEO",
            "recNkesv5Kmm1Az57",
            "rechnJA7vTowW2b5y",
            "recJUxFSb0eBe3zce",
            "recT13WkVSxT3P8wY",
            "recddJKK6vbn1udyH",
            "recZCfbZTXQhziOJ1",
            "recFVlsjjUHuLuPK1",
            "recGGT9fk8vVfdgsb",
            "recVWBOQRQos2uQsa",
            "rechZemhPUNr4yniA",
            "recRPPSp7suRHXhxP",
            "rectbfqOfL1zXeXKk",
            "rec6wquMpQLtDlz6r",
            "recA5k6xzxVWUjLgW",
            "recaTJZ2XiIgYH19Z",
            "recT0EBER5SVNsuWD",
            "recI92yh0AaXxoTk2",
            "rec0hA6TZu6ZkGnTG",
            "rec7438mhJerzgRQV",
            "recJOPveB5eGDIQ2q",
            "rec7na42NMvUNY8G4",
            "recRi9Ku7eu2fMQAN",
            "recklxBF7DZ2gFUGD",
            "recowa3vO2VAambCw",
            "recWrEpqitVW4NPqS",
            "recUnrWGVQeKlNwfm",
            "rec6MyMavOMT8LLQW",
            "rect6krDlbYiIW3rk",
            "recHgEmSqkWwRI4iK",
            "recgQs2yFQudnL4XM"
          ]
        }
      },
      {
        _table: {
          _base: {
            _airtable: { requestTimeout: 300000 },
            _id: "appEy2iTLwkkVlSjn"
          },
          id: null,
          name: "Activities"
        },
        id: "receMqF6WqH2X5qzd",
        _rawJson: {
          id: "receMqF6WqH2X5qzd",
          fields: {
            Activity: "Coding and tech development",
            People: [
              "recsfWVZvXOlpuR8F",
              "rec3s3dZk2THG8Rzp",
              "reczeyT6i6ll2DvYF",
              "recn9avSF7hpDoIMy",
              "recZkjIT85uUqHhKb",
              "recNkesv5Kmm1Az57",
              "recQ3EWBouaNVMFUl",
              "recAEpXMeHZL68Eo7",
              "recjmdG1xcJCXlpge",
              "recQK1N25c23D88ZQ",
              "recGGT9fk8vVfdgsb",
              "recJwo4nkL3KTr7ZD",
              "rec6WBfo6MeXPiTOM",
              "recUno3lo2ZCcw7xM",
              "recqMCezKgbDzZNyS",
              "rectbfqOfL1zXeXKk",
              "rec545Not0QxJk3Pu",
              "recFoIVqD8cSddn5h",
              "recwZCP65xn0KHq67",
              "rec0SMApO02zm96ls",
              "recYyUkx8DnJqqNk0",
              "recMP0Z0oVeRkTU60",
              "rec0hA6TZu6ZkGnTG",
              "recqf2hDJfehPzXpe",
              "recGbgL63yxO1JvLP",
              "recwHLgWsUAlH4b3m",
              "recd1TJvR7I1chaXC",
              "rec7na42NMvUNY8G4",
              "recSGz7vdnGulzIuL",
              "reczDdp7Sbyp0d6ui",
              "recBnZhm3hlZ7yuql",
              "recfcm0tSrb0F57Y9",
              "recs3vlsI7vvv2VRa",
              "recBDNTsADwEGP36a",
              "recyO242tZGJ6Tbby",
              "recojdWyFc0y44Tmt",
              "recgQs2yFQudnL4XM"
            ]
          },
          createdTime: "2020-03-30T20:58:49.000Z"
        },
        fields: {
          Activity: "Coding and tech development",
          People: [
            "recsfWVZvXOlpuR8F",
            "rec3s3dZk2THG8Rzp",
            "reczeyT6i6ll2DvYF",
            "recn9avSF7hpDoIMy",
            "recZkjIT85uUqHhKb",
            "recNkesv5Kmm1Az57",
            "recQ3EWBouaNVMFUl",
            "recAEpXMeHZL68Eo7",
            "recjmdG1xcJCXlpge",
            "recQK1N25c23D88ZQ",
            "recGGT9fk8vVfdgsb",
            "recJwo4nkL3KTr7ZD",
            "rec6WBfo6MeXPiTOM",
            "recUno3lo2ZCcw7xM",
            "recqMCezKgbDzZNyS",
            "rectbfqOfL1zXeXKk",
            "rec545Not0QxJk3Pu",
            "recFoIVqD8cSddn5h",
            "recwZCP65xn0KHq67",
            "rec0SMApO02zm96ls",
            "recYyUkx8DnJqqNk0",
            "recMP0Z0oVeRkTU60",
            "rec0hA6TZu6ZkGnTG",
            "recqf2hDJfehPzXpe",
            "recGbgL63yxO1JvLP",
            "recwHLgWsUAlH4b3m",
            "recd1TJvR7I1chaXC",
            "rec7na42NMvUNY8G4",
            "recSGz7vdnGulzIuL",
            "reczDdp7Sbyp0d6ui",
            "recBnZhm3hlZ7yuql",
            "recfcm0tSrb0F57Y9",
            "recs3vlsI7vvv2VRa",
            "recBDNTsADwEGP36a",
            "recyO242tZGJ6Tbby",
            "recojdWyFc0y44Tmt",
            "recgQs2yFQudnL4XM"
          ]
        }
      },
      {
        _table: {
          _base: {
            _airtable: { requestTimeout: 300000 },
            _id: "appEy2iTLwkkVlSjn"
          },
          id: null,
          name: "Activities"
        },
        id: "recV8VeNDxE236vI5",
        _rawJson: {
          id: "recV8VeNDxE236vI5",
          fields: {
            Activity: "External Communications (Social, PR, copywriting, etc.)",
            People: [
              "recjw6WmYXG1Of2d3",
              "recjgI71Eztoo75u6",
              "rec0T0Cj2Ucone0dr",
              "recU1ll5uxDtZjiF2",
              "receHZLmqCDhFJwdQ",
              "recJUxFSb0eBe3zce",
              "recDG3j3xkNRRE0zq",
              "recqscGwDvl8720nB",
              "recf8EjgM3Z4UBppx",
              "rec8o73hH84GMuIEZ",
              "recnqGk7K7kKxJs2z",
              "recT0EBER5SVNsuWD",
              "recyemd67qgWLzIOC",
              "recszmSJ65MFm1nup",
              "recv73PzfJg1ZLwJW",
              "recRi9Ku7eu2fMQAN",
              "recJzFjuRJNqm7iHy",
              "recklxBF7DZ2gFUGD",
              "recowa3vO2VAambCw",
              "recSR0EZkQQSGEFzP",
              "recUP69y8G7ILamTz",
              "recUnrWGVQeKlNwfm",
              "recwYfAA7OuNpf4XP",
              "rec9QQNUtIK7CIPub",
              "recOFDPsBB8be2hEX",
              "recJqhUelPMYnsc4W",
              "rec3KZgJCYQdSqX5q"
            ]
          },
          createdTime: "2020-03-30T20:59:13.000Z"
        },
        fields: {
          Activity: "External Communications (Social, PR, copywriting, etc.)",
          People: [
            "recjw6WmYXG1Of2d3",
            "recjgI71Eztoo75u6",
            "rec0T0Cj2Ucone0dr",
            "recU1ll5uxDtZjiF2",
            "receHZLmqCDhFJwdQ",
            "recJUxFSb0eBe3zce",
            "recDG3j3xkNRRE0zq",
            "recqscGwDvl8720nB",
            "recf8EjgM3Z4UBppx",
            "rec8o73hH84GMuIEZ",
            "recnqGk7K7kKxJs2z",
            "recT0EBER5SVNsuWD",
            "recyemd67qgWLzIOC",
            "recszmSJ65MFm1nup",
            "recv73PzfJg1ZLwJW",
            "recRi9Ku7eu2fMQAN",
            "recJzFjuRJNqm7iHy",
            "recklxBF7DZ2gFUGD",
            "recowa3vO2VAambCw",
            "recSR0EZkQQSGEFzP",
            "recUP69y8G7ILamTz",
            "recUnrWGVQeKlNwfm",
            "recwYfAA7OuNpf4XP",
            "rec9QQNUtIK7CIPub",
            "recOFDPsBB8be2hEX",
            "recJqhUelPMYnsc4W",
            "rec3KZgJCYQdSqX5q"
          ]
        }
      }
    ]
  }

  read(id) {
    return {
      _table: {
        _base: {
          _airtable: { requestTimeout: 300000 },
          _id: "appEy2iTLwkkVlSjn"
        },
        id: null,
        name: "Activities"
      },
      id: "rectcoBS7nwkJspXB",
      _rawJson: {
        id: "rectcoBS7nwkJspXB",
        fields: {
          Activity: "Research and data collection",
          People: [
            "recd393lV15mkoHVC",
            "recsfWVZvXOlpuR8F",
            "rec3s3dZk2THG8Rzp",
            "recl7TUn6hCJYY9ga",
            "reczeyT6i6ll2DvYF",
            "recnnckGJ8w8usZEO",
            "recOdRQRXtbW4gNxo",
            "recn9avSF7hpDoIMy",
            "rec0T0Cj2Ucone0dr",
            "recZkjIT85uUqHhKb",
            "recQ3EWBouaNVMFUl",
            "recwvQ0ko7zTEOXY5",
            "recY6xx8Tr9HVs9XR",
            "receHZLmqCDhFJwdQ",
            "recxad0JZwZ0WIpjR",
            "recZCfbZTXQhziOJ1",
            "recGGT9fk8vVfdgsb",
            "recJwo4nkL3KTr7ZD",
            "recQAv73DOHjEbFK0",
            "rec6WBfo6MeXPiTOM",
            "recVWBOQRQos2uQsa",
            "rechZemhPUNr4yniA",
            "recRPPSp7suRHXhxP",
            "recUqC2ygToF2A7yf",
            "rec9VSdlU70HrMEvZ",
            "rec6wquMpQLtDlz6r",
            "recaTJZ2XiIgYH19Z",
            "receKpJhNVxYokCMj",
            "rec8oz0RSoEXhUq1w",
            "rec7438mhJerzgRQV",
            "recSGjDLxa7r84ev2",
            "recWfCIrpTvfwl0cC",
            "rec7na42NMvUNY8G4",
            "recJzFjuRJNqm7iHy",
            "recklxBF7DZ2gFUGD",
            "recowa3vO2VAambCw",
            "recWrEpqitVW4NPqS",
            "recBnZhm3hlZ7yuql",
            "recUP69y8G7ILamTz",
            "recUnrWGVQeKlNwfm",
            "rec6MyMavOMT8LLQW",
            "recfcm0tSrb0F57Y9",
            "recOFDPsBB8be2hEX",
            "recDmIhXWCozc2r30",
            "rect6krDlbYiIW3rk",
            "recJqhUelPMYnsc4W",
            "recojdWyFc0y44Tmt",
            "recXI84yLdxZ9YIM2",
            "recxAEz9MhNn5IwwQ",
            "recgQs2yFQudnL4XM",
            "recsiA3JLjicbFjPv",
            "reciH2KMtduQ804UE",
            "recEcr2qZumQJUncK",
            "recLBodzer6FnsruU",
            "recuT1ASM9yxmit40"
          ]
        },
        createdTime: "2020-03-30T20:58:49.000Z"
      },
      fields: {
        Activity: "Research and data collection",
        People: [
          "recd393lV15mkoHVC",
          "recsfWVZvXOlpuR8F",
          "rec3s3dZk2THG8Rzp",
          "recl7TUn6hCJYY9ga",
          "reczeyT6i6ll2DvYF",
          "recnnckGJ8w8usZEO",
          "recOdRQRXtbW4gNxo",
          "recn9avSF7hpDoIMy",
          "rec0T0Cj2Ucone0dr",
          "recZkjIT85uUqHhKb",
          "recQ3EWBouaNVMFUl",
          "recwvQ0ko7zTEOXY5",
          "recY6xx8Tr9HVs9XR",
          "receHZLmqCDhFJwdQ",
          "recxad0JZwZ0WIpjR",
          "recZCfbZTXQhziOJ1",
          "recGGT9fk8vVfdgsb",
          "recJwo4nkL3KTr7ZD",
          "recQAv73DOHjEbFK0",
          "rec6WBfo6MeXPiTOM",
          "recVWBOQRQos2uQsa",
          "rechZemhPUNr4yniA",
          "recRPPSp7suRHXhxP",
          "recUqC2ygToF2A7yf",
          "rec9VSdlU70HrMEvZ",
          "rec6wquMpQLtDlz6r",
          "recaTJZ2XiIgYH19Z",
          "receKpJhNVxYokCMj",
          "rec8oz0RSoEXhUq1w",
          "rec7438mhJerzgRQV",
          "recSGjDLxa7r84ev2",
          "recWfCIrpTvfwl0cC",
          "rec7na42NMvUNY8G4",
          "recJzFjuRJNqm7iHy",
          "recklxBF7DZ2gFUGD",
          "recowa3vO2VAambCw",
          "recWrEpqitVW4NPqS",
          "recBnZhm3hlZ7yuql",
          "recUP69y8G7ILamTz",
          "recUnrWGVQeKlNwfm",
          "rec6MyMavOMT8LLQW",
          "recfcm0tSrb0F57Y9",
          "recOFDPsBB8be2hEX",
          "recDmIhXWCozc2r30",
          "rect6krDlbYiIW3rk",
          "recJqhUelPMYnsc4W",
          "recojdWyFc0y44Tmt",
          "recXI84yLdxZ9YIM2",
          "recxAEz9MhNn5IwwQ",
          "recgQs2yFQudnL4XM",
          "recsiA3JLjicbFjPv",
          "reciH2KMtduQ804UE",
          "recEcr2qZumQJUncK",
          "recLBodzer6FnsruU",
          "recuT1ASM9yxmit40"
        ]
      }
    }
  }
}
