# app and org for use with dashboard.serverless.com
app: cantstopcolumbus-api
org: maharris1011

service: api

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  jest:
    # You can pass jest options here
    # See details here: https://facebook.github.io/jest/docs/configuration.html
    # For instance, uncomment next line to enable code coverage
    # collectCoverage: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-jest-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    AIRTABLE_API_KEY: ${env:AIRTABLE_API_KEY}
    AIRTABLE_BASE: apppXeg0e2C1iuT8u
    PHOTOS_BUCKET: volunteer-photos
    REGION: ${opt:region, self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:DeleteObject
      Resource: "arn:aws:s3:::${self:provider.environment.PHOTOS_BUCKET}/*"
  apiGateway:
    restApiId:
      "Fn::ImportValue": CSCGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": CSCGW-rootResourceId

package:
  exclude:
    - .gitignore
    - README.md
    - tests/**
    - __mocks__/**
    
functions:
  promotions-create:
    handler: promotions/crud.create
    events:
      - http:
          path: promotions/
          method: post
          cors: true

  promotions-list:
    handler: promotions/crud.list
    events:
      - http:
          path: promotions/
          method: get
          cors: true

  volunteers-create:
    handler: volunteers/crud.create
    events:
      - http:
          path: volunteers/
          method: post
          cors: true

  volunteers-list:
    handler: volunteers/crud.list
    events:
      - http:
          path: volunteers/
          method: get
          cors: true          

  volunteers-read:
    handler: volunteers/crud.read
    events:
      - http:
          path: volunteers/{id}
          method: get
          cors: true          

  volunteers-update:
    handler: volunteers/crud.update
    events:
      - http:
          path: volunteers/{id}
          method: put
          cors: true          
        
  skills-list:
    handler: skills/crud.list
    events:
      - http:
          path: skills/
          method: get
          cors: true          

  skills-read:
    handler: skills/crud.read
    events:
      - http:
          path: skills/{id}
          method: get
          cors: true          

  categories-list:
    handler: categories/crud.list
    events:
      - http:
          path: categories/
          method: get
          cors: true          

  categories-read:
    handler: categories/crud.read
    events:
      - http:
          path: categories/{id}
          method: get
          cors: true          

  projects-list:
    handler: projects/crud.list
    events:
      - http:
          path: projects/
          method: get
          cors: true          

  projects-read:
    handler: projects/crud.read
    events:
      - http:
          path: projects/{id}
          method: get
          cors: true          

  impact-list:
    handler: impact/crud.list
    events:
      - http:
          path: impact/
          method: get
          cors: true          

  impact-read:
    handler: impact/crud.read
    events:
      - http:
          path: impact/{id}
          method: get
          cors: true          

  activities-list:
    handler: activities/crud.list
    events:
      - http:
          path: activities/
          method: get
          cors: true          

  activities-read:
    handler: activities/crud.read
    events:
      - http:
          path: activities/{id}
          method: get
          cors: true          

  measurements-list:
    handler: measurements/crud.list
    events:
      - http:
          path: measurements/
          method: get
          cors: true          

  measurements-read:
    handler: measurements/crud.read
    events:
      - http:
          path: measurements/{id}
          method: get
          cors: true          
                  
  partners-list:
    handler: partners/crud.list
    events:
      - http:
          path: partners/
          method: get
          cors: true          

  partners-read:
    handler: partners/crud.read
    events:
      - http:
          path: partners/{id}
          method: get
          cors: true          
        
resources:
  Resources:
    PhotosBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${self:provider.environment.PHOTOS_BUCKET}