# app and org for use with dashboard.serverless.com
app: cantstopcolumbus-api
org: maharris1011

service: api

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  jest:
    # You can pass jest options here
    # See details here: https://facebook.github.io/jest/docs/configuration.html
    # For instance, uncomment next line to enable code coverage
    # collectCoverage: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-jest-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    AIRTABLE_API_KEY: ${env:AIRTABLE_API_KEY}
    AIRTABLE_BASE: apppXeg0e2C1iuT8u
    PROMOTIONS_VIEW: "10TV Promos"
    CATEGORIES: Categories
    SKILLS: Skills
    VOLUNTEERS: People
  apiGateway:
    restApiId:
      "Fn::ImportValue": CSCGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": CSCGW-rootResourceId

package:
  exclude:
    - .gitignore
    - README.md
    - tests/**
    - __mocks__/**
    
functions:
  promotions-create:
    handler: promotions/crud.create
    events:
      - http:
          path: promotions/
          method: post
          cors: true

  promotions-list:
    handler: promotions/crud.list
    events:
      - http:
          path: promotions/
          method: get
          cors: true

  volunteers-create:
    handler: volunteers/crud.create
    events:
      - http:
          path: volunteers/
          method: post
          cors: true

  volunteers-list:
    handler: volunteers/crud.list
    events:
      - http:
          path: volunteers/
          method: get
          cors: true          

  volunteers-read:
    handler: volunteers/crud.read
    events:
      - http:
          path: volunteers/{id}
          method: get
          cors: true          
                                