# This is a basic workflow to help you get started with Actions

name: Deploy via Serverless

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "buildAndDeploy"
  buildAndDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}   

    steps:
    - name: Check out my code
      uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install dependencies
      run: |
        npm install
      working-directory: ./api

    - name: Deploy to AWS
      run: serverless deploy -v -s dev
      working-directory: "./api"

    # - name: Deploy the API
    #   uses: aaronpanch/action-serverless@v1.0.0
    #   env:
    #     SERVICE_ROOT: api
    #   with:
    #     args: deploy
  
